spring.application.name=work
spring.datasource.url=jdbc:mysql://localhost:3306/crud_db
spring.datasource.username=root
spring.datasource.password=Siddhu@3343

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
